### ISSUE TITLE
不用pod、不用carthage，直接导入SwiftProgressHUD文件不是更方便吗？

### ISSUE THREAD

**Issue by yuankai01** [stackhou/SwiftProgressHUD#1]
另外，可以加个类方法，传入对应时间后隐藏
    
//加载对应时间后完成
    public class func hideAfterDlay(time: Int) -> Void {
        DispatchQueue.main.asyncAfter(deadline: .now() + .seconds(time)) {
            SwiftProgressHUD.hideAllHUD()
        }
    }

**Comment by stackhou** [comment]
1、cocoapods、carthage、还是手动个人喜好怎么使用
2.原本每个方法都有 自动加载完成的时间设置 autoClearTime ,有相应的默认值，根据不同需求修改，没有必要设置该类方法
